### ISSUE TITLE
*.bak is not accessable & not valid srt

### ISSUE THREAD

**Issue by testbughub** [helixarch/subedit#13]
Hi!

First of all, thank you for this. It has helped me multiple times, and I can't live without it now. 

Now for my issue. 

This first srt file works fine:
https://pastebin.com/W5hBj7js

But this doesn't for some reason:
https://pastebin.com/DFyDyb2Q

Am I missing something?

**Comment by helixarch** [comment]
bak stands for backup, if you want to use it, just rename it and remove the .bak extension

**Comment by testbughub** [comment]
I know, it's the error I get when I try to shift the time.
https://imgur.com/a/J4YFjs6

**Comment by helixarch** [comment]
It seems that the file's permissions have been changed for some reason, making it is not readable. Try changing permissions first with chmod +r name_of_the_file

**Comment by testbughub** [comment]
Nope, that's not either. I'm a intermediate/advanced Linux user, so I know how permissions work. I can fix issues like these most of the time, but because of how large this file is, I'm having trouble finding the cause.
https://imgur.com/a/XatMorR

**Comment by ody1** [comment]
@testbughub

**Comment by ody1** [comment]
@testbughub 
Thank you for your kind words.

The problematic srt has a single space at the end of every time string.
The regular expression that is used to parse the srt files was vary strict, so the file was not detected to be a valid srt subtitle.

Fixed it in the last commit [8f44af9](https://github.com/helixarch/subedit/commit/8f44af92917321151c7e24788311462189330882).

**Comment by testbughub** [comment]
Ah, so that's what it was! Never noticed it before.
So glad you figured it out.
Thanks again!
